language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - android-29
    - build-tools-29.0.3
script: gradle build -PRefitted_IdentityPoolId="X" -PRefitted_OpenIdSource="X"