[versions]
activityKtx = "1.9.1"
arrowStack = "1.2.4"
awsAndroidSdkCore = "2.76.0"
awsAndroidSdkDdbMapper = "2.76.0"
composeBom = "2024.06.00"
coreKtx = "1.13.1"
coreRuntime = "2.2.0"
espressoCore = "3.6.1"
firebaseBom = "33.1.2"
hiltAndroid = "2.51.1"
hiltNavigationCompose = "1.2.0"
junitJupiterApi = "5.10.3"
legacySupportV4 = "1.0.0"
navigationCompose = "2.7.7"
pagingCommonKtx = "3.3.1"
playServicesAuth = "21.2.0"
roomPaging = "2.6.1"
runner = "1.6.1"
truth = "1.4.4"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-common = { module = "androidx.arch.core:core-common", version.ref = "coreRuntime" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "coreRuntime" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "pagingCommonKtx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingCommonKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomPaging" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomPaging" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
arrow-core = { module = "io.arrow-kt:arrow-core" }
arrow-stack = { module = "io.arrow-kt:arrow-stack", version.ref = "arrowStack" }
aws-android-sdk-core = { module = "com.amazonaws:aws-android-sdk-core", version.ref = "awsAndroidSdkCore" }
aws-android-sdk-ddb-mapper = { module = "com.amazonaws:aws-android-sdk-ddb-mapper", version.ref = "awsAndroidSdkDdbMapper" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]