name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - '.github/workflows/android.yml'
      - '*gradle*'
  pull_request:
    branches: [ master ]
    paths:
      - 'app/**'
      - '.github/workflows/android.yml'
      - '*gradle*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode google-services.json
      env: 
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      run: echo $FIREBASE_SECRET | base64 --decode > app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        ID_POOLID: ${{ secrets.REFITTED_IDENTITYPOOLID }}
        OPENID_SOURCE: ${{ secrets.REFITTED_OPENIDSOURCE }}
      run: ./gradlew assembleMinDebug -PRefitted_IdentityPoolId="$ID_POOLID" -PRefitted_OpenIdSource="ID_POOLID"

  block-fixup:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Block fixup commit merge
      uses: 13rac1/block-fixup-merge-action@v2.0.0
