name: Web CI

on:
  push:
    branches: [ master ]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.17
      uses: actions/setup-node@v3
      with:
        node-version: 16.17
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'

    - run: npm ci
      working-directory: web

    - run: npm run build
      working-directory: web
      